services:
    server:
        build: ./backend
        container_name: server
        ports:
            - "5000:5000"
        volumes:
            - server-data:/app/data
        env_file: ./backend/.env

    client:
        build: ./frontend
        container_name: client
        ports:
            - "3000:3000"
        stdin_open: true
        tty: true

volumes:
    server-data:
